managed_node:
  hosts:
    ec2_instance:
      ansible_host: <HOST_ADDR>
      ansible_user: <HOST_USERNAME>
      ansible_connection: ssh
      ansible_ssh_private_key_file: <SSH_PRIVATE_KEY_FILE_PATH>
