- name: Setup Docker and Docker Compose on EC2
  hosts: ec2_instance
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      register: update_result

    - name: Install pip
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Install Docker
      ansible.builtin.dnf:
        name: docker
        state: present

    - name: Ensure system requests package is removed
      ansible.builtin.dnf:
        name: python3-requests
        state: absent

    - name: Install Docker SDK
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker
        - containerd

    - name: Download Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Create symlink for Docker Compose
      ansible.builtin.file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Copy docker-compose.yaml to remote
      ansible.builtin.copy:
        src: ../docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
        owner: ec2-user
        group: ec2-user
        mode: "0644"

    - name: Copy ELK stack config files to remote
      ansible.builtin.copy:
        src: ../config
        dest: /home/ec2-user
        owner: ec2-user
        group: ec2-user
        mode: "0644"

    - name: Copy Environment Variables File
      ansible.builtin.copy:
        src: ../.env
        dest: /home/ec2-user
        owner: ec2-user
        group: ec2-user
        mode: "0644"

    - name: Load secret definitions
      ansible.builtin.set_fact:
        secret_file: "{{ lookup('file', '../secrets/secrets.yaml') | from_yaml }}"

    - name: Create Docker secrets from values
      community.docker.docker_secret:
        name: "{{ item.name }}"
        data: "{{ item.value }}"
        state: present
      loop: "{{ secret_file.secrets }}"
