version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
  app:
    depends_on:
      - mongo
    image: tahabozdemir/linksaver:latest
    restart: always
    environment:
      - LINKSAVER_AUTH_DB_NAME=${LINKSAVER_AUTH_DB_NAME}
      - LINKSAVER_DB_HOST=mongo
      - LINKSAVER_DB_PORT=${LINKSAVER_DB_PORT}
      - LINKSAVER_DB_NAME=${LINKSAVER_DB_NAME}
      - LINKSAVER_DB_USER=${DB_USER}
      - LINKSAVER_DB_PASS=${DB_PASS}
      - LINKSAVER_ISSUER_URI=${LINKSAVER_ISSUER_URI}
      - LINKSAVER_JWK_SET_URI=${LINKSAVER_JWK_SET_URI}
      - AWS_REGION=${AWS_REGION}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - TEST_USER_EMAIL=${TEST_USER_EMAIL}
      - TEST_USER_PASS=${TEST_USER_PASS}
      - API_KEY=${API_KEY}
    ports:
      - "80:8080"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${EXP_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXP_PASS}

    depends_on:
      - mongo

volumes:
  db_data:
