version: "3.8"

services:
  mongo:
    deploy:
      replicas: 1
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    env_file: .env

  app:
    deploy:
      replicas: 1
    depends_on:
      - mongo
    image: tahabozdemir/linksaver:latest
    restart: always
    environment:
      LINKSAVER_AUTH_DB_NAME: ${LINKSAVER_AUTH_DB_NAME}
      LINKSAVER_DB_HOST: mongo
      LINKSAVER_DB_PORT: ${LINKSAVER_DB_PORT}
      LINKSAVER_DB_NAME: ${LINKSAVER_DB_NAME}
      LINKSAVER_DB_USER: ${DB_USER}
      LINKSAVER_DB_PASS: /run/secrets/db-password
      LINKSAVER_ISSUER_URI: ${LINKSAVER_ISSUER_URI}
      LINKSAVER_JWK_SET_URI: ${LINKSAVER_JWK_SET_URI}
      AWS_REGION: ${AWS_REGION}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      TEST_USER_EMAIL: /run/secrets/test-user-email
      TEST_USER_PASS: /run/secrets/test-user-password
      API_KEY: /run/secrets/api-key
    secrets:
      - db-password
      - test-user-email
      - test-user-password
      - api-key
    ports:
      - "80:8080"
    volumes:
      - ./logs:/logs
    env_file: .env

  mongo-express:
    deploy:
      replicas: 1
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/db-password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${EXP_USER}
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/express-password
    secrets:
      - db-password
      - express-password
    depends_on:
      - mongo
    env_file: .env

  elasticsearch:
    image: elasticsearch:8.14.3
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:Z
      - ./config/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
    ports:
      - 9200:9200
    environment:
      node.name: elasticsearch
      cluster.name: docker-cluster
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    restart: unless-stopped
    networks:
      - elk
    depends_on:
      - app

  logstash:
    image: logstash:8.14.3
    container_name: logstash
    volumes:
      - ./config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      - ./logs:/logs
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    command: bin/logstash -f /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - elk
    deploy:
      replicas: 1

  kibana:
    image: kibana:8.14.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: overlay

secrets:
  api-key:
    external: true
  db-password:
    external: true
  express-password:
    external: true
  test-user-email:
    external: true
  test-user-password:
    external: true

volumes:
  db_data:
  elasticsearch:
