version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

  app:
    depends_on:
      - mongo
    image: tahabozdemir/linksaver:latest
    environment:
      - LINKSAVER_AUTH_DB_NAME=${LINKSAVER_AUTH_DB_NAME}
      - LINKSAVER_DB_HOST=mongo
      - LINKSAVER_DB_PORT=${LINKSAVER_DB_PORT}
      - LINKSAVER_DB_NAME=${LINKSAVER_DB_NAME}
      - LINKSAVER_DB_USER=${DB_USER}
      - LINKSAVER_DB_PASS=${DB_PASS}
      - LINKSAVER_ISSUER_URI=${LINKSAVER_ISSUER_URI}
      - LINKSAVER_JWK_SET_URI=${LINKSAVER_JWK_SET_URI}
      - AWS_REGION=${AWS_REGION}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - TEST_USER_EMAIL=${TEST_USER_EMAIL}
      - TEST_USER_PASS=${TEST_USER_PASS}
      - API_KEY=${API_KEY}
    ports:
      - "80:8080"
    volumes:
      - ./logs:/logs

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${EXP_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXP_PASS}
    depends_on:
      - mongo

  elasticsearch:
    image: elasticsearch:8.14.3
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:Z
      - ./config/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
    ports:
      - 9200:9200
    environment:
      node.name: elasticsearch
      cluster.name: docker-cluster
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    networks:
      - elk
    depends_on:
      - app

  logstash:
    image: logstash:8.14.3
    container_name: logstash
    volumes:
      - ./config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      - ./logs:/logs
    ports:
      - 50000:50000/tcp
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    command: bin/logstash -f /usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.14.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  db_data:
  elasticsearch:
